import type { Metadata } from 'next'
import './globals.css'
import { ThemeProvider } from 'next-themes'
import { BackToTop } from '@/components/back-to-top'
import { ContactWhatsApp } from '@/components/contact-whatsApp'
import { Roboto, Open_Sans, Oswald } from 'next/font/google'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '500', '700'], // regular, medium, bold
  style: ['normal', 'italic'], // inclui o italic
  variable: '--font-roboto',
})

export const openSans = Open_Sans({
  subsets: ['latin'],
  weight: ['400'], // Regular
  variable: '--font-open-sans',
})

export const oswald = Oswald({
  subsets: ['latin'],
  weight: ['400'], // Regular
  variable: '--font-oswald',
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    // <html lang="en" className="dark">
    //   <body>{children}</body>
    // </html>
    <html
      lang="pt-BR"
      suppressHydrationWarning
      className={`${roboto.variable} ${openSans.variable} ${oswald.variable}`}
    >
      <body className="font-roboto antialiased">
        <BackToTop />
        <ContactWhatsApp />
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
